/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package production;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Peter
 */
public class NewWorker extends javax.swing.JFrame {

    
    ProductionSite site;
    /**
     * Creates new form NewWorker
     */
    public NewWorker() {
        initComponents();
        jComboBox1 = new JComboBox(WorkerPosition.AllPositions());
        jComboBox1.setSelectedIndex(0);
        this.site = null;
    }
    
    public NewWorker(ProductionSite s) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setVisible(true);
        //jComboBox1 = new JComboBox(WorkerPosition.AllPositions());
        jComboBox1.removeAllItems();
        for(String str : WorkerPosition.AllPositions())
        {
            jComboBox1.addItem(str);
        }
        jComboBox1.setSelectedIndex(0);
        this.site = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Worker");
        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Full Name: ");
        jLabel1.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(53, 16));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Log In Username: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(53, 16));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Log In Password: ");
        jLabel3.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(53, 16));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Position: ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Salary / Hour: ");
        jLabel5.setMaximumSize(new java.awt.Dimension(53, 16));
        jLabel5.setMinimumSize(new java.awt.Dimension(53, 16));
        jLabel5.setPreferredSize(new java.awt.Dimension(53, 16));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.setMaximumSize(new java.awt.Dimension(130, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(130, 50));
        jButton1.setPreferredSize(new java.awt.Dimension(130, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel7.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel7.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel8.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel8.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel9.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel9.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel10.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel10.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel11.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel11.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setMaximumSize(new java.awt.Dimension(247, 22));
        jLabel12.setMinimumSize(new java.awt.Dimension(247, 22));
        jLabel12.setPreferredSize(new java.awt.Dimension(247, 22));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Hours / Day: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        boolean withoutErrors = true;
        double salary = 0, hours = 0;
        
        
        
        if(jTextField1.getText().equals(""))
        {
            jLabel7.setText("Empty!");
            withoutErrors = false;
        }
        else
        {
            String fullname = jTextField1.getText();
            boolean nonaplha = true;
            for(char c : fullname.toCharArray())
            {
                if(!Character.isAlphabetic(c) && c != ' ')
                {
                    withoutErrors = false;
                    nonaplha = false;
                    jLabel7.setText("Only letters allowed!");
                    break;
                }
            }
            if(nonaplha)
            {
                jLabel7.setText("");
            }
        }
        
        if(jTextField2.getText().equals(""))
        {
            jLabel8.setText("Empty");
            withoutErrors = false;
        }
        else
        {
            jLabel8.setText("");
        }
        
        if(jTextField3.getText().equals(""))
        {
            jLabel9.setText("Empty");
            withoutErrors = false;
        }
        else
        {
            jLabel9.setText("");
        }
        
        if(jTextField5.getText().equals(""))
        {
            jLabel12.setText("Empty");
            withoutErrors = false;
        }
        else
        {
            try
            {
                salary = Double.parseDouble(jTextField5.getText());
                jLabel12.setText("");
            }
            catch(Exception e)
            {
                jLabel12.setText("Only decimals allowed!");
                withoutErrors = false;
            }
        }
        
        if(jTextField6.getText().equals(""))
        {
            jLabel11.setText("Empty");
            withoutErrors = false;
        }
        else
        {
            try
            {
                hours = Double.parseDouble(jTextField6.getText());
                jLabel11.setText("");
            }
            catch(Exception e)
            {
                jLabel11.setText("Only decimals allowed!");
                withoutErrors = false;
            }
        }
        
        if(withoutErrors)
        {
            if(NewSaveWorker())
            {
                site.AddWorker(new Worker(jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), (String) jComboBox1.getSelectedItem(), salary, hours));
                JOptionPane.showMessageDialog(this, "New Worker Added!");
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error with Json file!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean NewSaveWorker()
    {
        JSONObject ob;
        JSONParser parser = new JSONParser();
        
        try {
            ob = (JSONObject) parser.parse(DataSet.jsonString);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex);
            return false;
        }
        
        JSONArray array = (JSONArray) ob.get("sites");
        ArrayList<JSONObject> list = new ArrayList<>();
        
        for (Iterator it = array.iterator(); it.hasNext();) {
            JSONObject o = (JSONObject) it.next();
            list.add(o);
        }
        
        for(JSONObject obj : list)
        {
            if(obj.get("ID").equals(site.ID))
            {
                if(obj.get("workers") == null)
                {
                    JSONObject worker = new JSONObject();
                    worker.put("fullName", jTextField1.getText());
                    worker.put("loginName", jTextField2.getText());
                    worker.put("loginPass", jTextField3.getText());
                    worker.put("position", (String) jComboBox1.getSelectedItem());
                    worker.put("salary", Double.parseDouble(jTextField5.getText()));
                    worker.put("hours", Double.parseDouble(jTextField6.getText()));
                    obj.put("workers", worker);
                }
                else
                {
                    JSONArray array2 = (JSONArray) ob.get("workers");
                    ArrayList<JSONObject> list2 = new ArrayList<>();
                    JSONObject worker = new JSONObject();
                    worker.put("fullName", jTextField1.getText());
                    worker.put("loginName", jTextField2.getText());
                    worker.put("loginPass", jTextField3.getText());
                    worker.put("position", (String) jComboBox1.getSelectedItem());
                    worker.put("salary", Double.parseDouble(jTextField5.getText()));
                    worker.put("hours", Double.parseDouble(jTextField6.getText()));

                    for (Iterator it2 = array2.iterator(); it2.hasNext();) {
                        JSONObject o = (JSONObject) it2.next();
                        list2.add(o);
                    }
                    list2.add(worker);
                    obj.put("workers", list2);
                }
            }
        }
        
        JSONObject sites = new JSONObject();
        sites.put("sites", list);
        
        try {
            DataSet.Initialize();
            DataSet.Write(sites);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Production.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        
        return true;
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewWorker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewWorker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
